"""
Run the whole pipeline with one command:

    python3 src/run_all.py

    1. regenerate the synthetic datasets      -> data/*.csv
    2. rebuild the SQLite warehouse           -> data/hr.db
    3. run the three analyses                 -> reports/figures/*.svg
    4. assemble the findings report           -> reports/findings.md

Output is deterministic: same seed, same numbers, same charts, every time.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import analysis_attrition
import analysis_pay_gap
import analysis_service_desk
import build_db
import generate_data
from hrlib import ROOT, SNAPSHOT, WINDOW_START

REPORT = ROOT / "reports" / "findings.md"

HEADER = f"""# People Analytics - findings

**Reporting period:** {WINDOW_START:%d %B %Y} to {SNAPSHOT:%d %B %Y}
**Population:** a synthetic European shared-services organisation across Italy, Poland,
Germany and Spain
**Generated by:** `python3 src/run_all.py` - every number and chart below is reproduced
from the code in this repository

> The data is synthetic and generated with a fixed seed (`src/generate_data.py`). No real
> employee data is used anywhere in this project. The analytical methods, the metric
> definitions and the recommendations are the parts meant to be judged.

---

"""

FOOTER = """
---

## Method, assumptions and limits

**Definitions.** Turnover is exits over the period as a percentage of *average* headcount,
not closing headcount. Voluntary and involuntary exits are reported separately, because
mixing them hides the number that management can act on. The tenure curve uses
person-months at risk as the denominator, so employees who move between tenure bands
during the year are counted where they actually were.

**The driver model** is a logistic regression fitted on a feature window (Jul-Sep 2025) with
the outcome measured in the following nine months. Predictors are therefore always observed
before the exit they predict, and every employee in the sample carries the same exposure.
Odds ratios describe association, not causation: they rank risk and point at where to look.

**The pay-gap model** is OLS on log(base salary), so coefficients read as percentage
differences. Controls are added in blocks - level, then department, then country, tenure and
contract - to separate a like-for-like pay difference from a structural one. Adjusted gaps
should never be reported on their own: if women are under-represented at senior levels, the
model will explain away exactly the gap the organisation most needs to close.

**Stated assumptions.** Replacement cost is 30% of annual base salary, the mid-point of the
range commonly cited for non-executive roles. Agent handling effort is 40 minutes per case
and 1,600 productive hours per FTE per year. Deflection assumes a quarter of the volume in
the two largest categories can be self-served. Each of these is a lever: change it in
`src/hrlib.py` or `src/analysis_service_desk.py` and every dependent number updates.

**Limits.** Single organisation, twelve months, synthetic data. Pay-gap categories below
roughly 50 employees have wide confidence intervals and are marked accordingly. Nothing here
is legal advice on Directive (EU) 2023/970; the thresholds are modelled to show what the
reporting exercise involves.
"""


def main() -> None:
    print("1/4  generating synthetic data")
    generate_data.main()

    print("\n2/4  building the SQLite warehouse")
    build_db.main()

    print("\n3/4  running analyses")
    sections = []
    for name, module in (("attrition & retention", analysis_attrition),
                         ("pay equity", analysis_pay_gap),
                         ("service desk", analysis_service_desk)):
        sections.append(module.run())
        print(f"     - {name}")

    print("\n4/4  writing the report")
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    body = "\n\n".join(section.rstrip() + "\n" for section in sections)
    REPORT.write_text(HEADER + body + FOOTER, encoding="utf-8")

    figures = sorted((ROOT / "reports" / "figures").glob("*.svg"))
    print(f"     reports/findings.md  ({REPORT.stat().st_size / 1024:.0f} KB)")
    print(f"     reports/figures/     ({len(figures)} charts)")
    print("\nDone. Open reports/findings.md, or run `python3 src/run_sql.py` for the SQL layer.")


if __name__ == "__main__":
    main()
